global:
  domain: argocd.robertbatson.com

configs:
  params:
    server.insecure: true

server:
  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
      nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
      cert-manager.io/cluster-issuer: "cloudflare-letsencrypt-prod"
    extraTls:
      - hosts:
        - argocd.robertbatson.com
        # Based on the ingress controller used secret might be optional
        secretName: argocd-tls