longhornUI:
  # -- Replica count for Longhorn UI.
  replicas: 1

ingress:
  # -- Setting that allows Longhorn to generate ingress records for the Longhorn UI service.
  enabled: true

  # -- IngressClass resource that contains ingress configuration, including the name of the Ingress controller.
  # ingressClassName can replace the kubernetes.io/ingress.class annotation used in earlier Kubernetes releases.
  ingressClassName: "nginx"

  # -- Hostname of the Layer 7 load balancer.
  host: longhorn.robertbatson.com
  tls: true
  tlsSecret: longhorn-ui-tls
  annotations:
    cert-manager.io/cluster-issuer: "cloudflare-letsencrypt-prod"
 