apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: alertmanager-config
  namespace: monitoring
  labels:
    alertmanagerConfig: main
spec:
  route:
    groupBy: ['alertname', 'job']
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 12h
    receiver: 'discord-notifications'
    routes:
    - receiver: 'discord-notifications'
      matchers:
        - name: severity
          value: critical
  receivers:
  - name: 'discord-notifications'
    discordConfigs:
      - apiURL:
          name: discord-webhook-url
          key: url
